// Code generated by scripts/gen-selectors.mjs from src/testing/selectors.json. DO NOT EDIT.

// Package selectors holds the data-testid CSS selectors shared with the app.
package selectors

type pageStateSelectors struct {
	Content string
	Error   string
}

// PageState selectors.
var PageState = pageStateSelectors{
	Content: `[data-testid="page-content"]`,
	Error:   `[data-testid="page-error"]`,
}

type homeSelectors struct {
	Root  string
	Title string
}

// Home selectors.
var Home = homeSelectors{
	Root:  `[data-testid="home-root"]`,
	Title: `[data-testid="home-title"]`,
}
