// Code generated by scripts/gen-selectors.mjs from src/testing/selectors.json. DO NOT EDIT.

// Package selectors holds the data-testid CSS selectors shared with the app.
package selectors

type pageStateSelectors struct {
	Content string
	Error   string
	Loading string
}

// PageState selectors.
var PageState = pageStateSelectors{
	Content: `[data-testid="page-content"]`,
	Error:   `[data-testid="page-error"]`,
	Loading: `[data-testid="page-loading"]`,
}

type homeSelectors struct {
	Root       string
	Title      string
	BookCount  string
	ScanAction string
	AskBooky   string
}

// Home selectors.
var Home = homeSelectors{
	Root:       `[data-testid="home-root"]`,
	Title:      `[data-testid="home-title"]`,
	BookCount:  `[data-testid="home-book-count"]`,
	ScanAction: `[data-testid="home-scan-action"]`,
	AskBooky:   `[data-testid="home-ask-booky"]`,
}

type tabsSelectors struct {
	Shelf    string
	Scan     string
	Loans    string
	Groups   string
	Settings string
}

// Tabs selectors.
var Tabs = tabsSelectors{
	Shelf:    `[data-testid="tab-shelf"]`,
	Scan:     `[data-testid="tab-scan"]`,
	Loans:    `[data-testid="tab-loans"]`,
	Groups:   `[data-testid="tab-groups"]`,
	Settings: `[data-testid="tab-settings"]`,
}

type scanSelectors struct {
	Root  string
	Title string
}

// Scan selectors.
var Scan = scanSelectors{
	Root:  `[data-testid="scan-root"]`,
	Title: `[data-testid="scan-title"]`,
}

type loansSelectors struct {
	Root  string
	Title string
}

// Loans selectors.
var Loans = loansSelectors{
	Root:  `[data-testid="loans-root"]`,
	Title: `[data-testid="loans-title"]`,
}

type groupsSelectors struct {
	Root  string
	Title string
}

// Groups selectors.
var Groups = groupsSelectors{
	Root:  `[data-testid="groups-root"]`,
	Title: `[data-testid="groups-title"]`,
}

type settingsSelectors struct {
	Root  string
	Title string
}

// Settings selectors.
var Settings = settingsSelectors{
	Root:  `[data-testid="settings-root"]`,
	Title: `[data-testid="settings-title"]`,
}

type notFoundSelectors struct {
	Root     string
	Title    string
	HomeLink string
}

// NotFound selectors.
var NotFound = notFoundSelectors{
	Root:     `[data-testid="not-found-root"]`,
	Title:    `[data-testid="not-found-title"]`,
	HomeLink: `[data-testid="not-found-home-link"]`,
}

type loadingSelectors struct {
	Root  string
	Title string
}

// Loading selectors.
var Loading = loadingSelectors{
	Root:  `[data-testid="loading-root"]`,
	Title: `[data-testid="loading-title"]`,
}

type dbErrorSelectors struct {
	Root  string
	Title string
	Retry string
}

// DbError selectors.
var DbError = dbErrorSelectors{
	Root:  `[data-testid="db-error-root"]`,
	Title: `[data-testid="db-error-title"]`,
	Retry: `[data-testid="db-error-retry"]`,
}

type emptyStateSelectors struct {
	Root   string
	Action string
}

// EmptyState selectors.
var EmptyState = emptyStateSelectors{
	Root:   `[data-testid="empty-state"]`,
	Action: `[data-testid="empty-state-action"]`,
}

type bookySelectors struct {
	Avatar     string
	Bubble     string
	BubbleText string
	Dismiss    string
	Action     string
	TipHost    string
}

// Booky selectors.
var Booky = bookySelectors{
	Avatar:     `[data-testid="booky-avatar"]`,
	Bubble:     `[data-testid="booky-bubble"]`,
	BubbleText: `[data-testid="booky-bubble-text"]`,
	Dismiss:    `[data-testid="booky-dismiss"]`,
	Action:     `[data-testid="booky-action"]`,
	TipHost:    `[data-testid="booky-tip-host"]`,
}
