// Code generated by scripts/gen-selectors.mjs from src/testing/selectors.json. DO NOT EDIT.

// Package selectors holds the data-testid CSS selectors shared with the app.
package selectors

type pageStateSelectors struct {
	Content string
	Error   string
}

// PageState selectors.
var PageState = pageStateSelectors{
	Content: `[data-testid="page-content"]`,
	Error:   `[data-testid="page-error"]`,
}

type homeSelectors struct {
	Root  string
	Title string
}

// Home selectors.
var Home = homeSelectors{
	Root:  `[data-testid="home-root"]`,
	Title: `[data-testid="home-title"]`,
}

type bookySelectors struct {
	Avatar        string
	Bubble        string
	BubbleMessage string
	BubbleDismiss string
	TipHost       string
}

// Booky selectors.
var Booky = bookySelectors{
	Avatar:        `[data-testid="booky-avatar"]`,
	Bubble:        `[data-testid="booky-bubble"]`,
	BubbleMessage: `[data-testid="booky-bubble-message"]`,
	BubbleDismiss: `[data-testid="booky-bubble-dismiss"]`,
	TipHost:       `[data-testid="booky-tip-host"]`,
}
