// Code generated by scripts/gen-selectors.mjs from src/testing/selectors.json. DO NOT EDIT.

export const Testids = {
  pageState: {
    content: 'page-content',
    error: 'page-error',
  },
  home: {
    root: 'home-root',
    title: 'home-title',
  },
  booky: {
    avatar: 'booky-avatar',
    bubble: 'booky-bubble',
    bubbleMessage: 'booky-bubble-message',
    bubbleDismiss: 'booky-bubble-dismiss',
    tipHost: 'booky-tip-host',
  },
} as const;
