// Code generated by scripts/gen-selectors.mjs from src/testing/selectors.json. DO NOT EDIT.

export const Testids = {
  pageState: {
    content: 'page-content',
    error: 'page-error',
    loading: 'page-loading',
  },
  home: {
    root: 'home-root',
    title: 'home-title',
    bookCount: 'home-book-count',
    scanAction: 'home-scan-action',
    askBooky: 'home-ask-booky',
  },
  tabs: {
    shelf: 'tab-shelf',
    scan: 'tab-scan',
    loans: 'tab-loans',
    groups: 'tab-groups',
    settings: 'tab-settings',
  },
  scan: {
    root: 'scan-root',
    title: 'scan-title',
  },
  loans: {
    root: 'loans-root',
    title: 'loans-title',
  },
  groups: {
    root: 'groups-root',
    title: 'groups-title',
  },
  settings: {
    root: 'settings-root',
    title: 'settings-title',
  },
  notFound: {
    root: 'not-found-root',
    title: 'not-found-title',
    homeLink: 'not-found-home-link',
  },
  loading: {
    root: 'loading-root',
    title: 'loading-title',
  },
  dbError: {
    root: 'db-error-root',
    title: 'db-error-title',
    retry: 'db-error-retry',
  },
  emptyState: {
    root: 'empty-state',
    action: 'empty-state-action',
  },
  booky: {
    avatar: 'booky-avatar',
    bubble: 'booky-bubble',
    bubbleText: 'booky-bubble-text',
    dismiss: 'booky-dismiss',
    action: 'booky-action',
    tipHost: 'booky-tip-host',
  },
  dialog: {
    root: 'dialog-root',
    confirm: 'dialog-confirm',
    cancel: 'dialog-cancel',
  },
  snackbar: {
    root: 'snackbar-root',
    action: 'snackbar-action',
  },
} as const;
